[project]
name = "appointment-booking"
version = "1.2.0"
description = "Bot for making appointment for massage"
readme = "README.md"
requires-python = ">=3.12,<3.15"
dependencies = [
    "aiocron>=2.1",
    "aiogram>=3.27.0",
    "aiosqlite>=0.22.1",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.14.0",
]
